- app/models/cart_item.rb
- app/models/order.rb
- db/migrate/20200222093448_devise_create_customers.rb
- db/migrate/20200223030950_create_cart_items.rb
- db/migrate/20200223033954_create_orders.rb
- db/migrate/20200223043554_add_last_name_to_customers.rb
- db/migrate/20200223043803_add_first_name_to_customers.rb
- db/migrate/20200223043916_add_last_name_kana_to_customers.rb
- db/migrate/20200223044041_add_first_name_kana_to_customers.rb
- db/migrate/20200223044317_add_post_code_to_customers.rb
- db/migrate/20200223044616_add_address_to_customers.rb
- db/migrate/20200223045547_add_phone_number_to_customers.rb
- db/migrate/20200223045724_add_is_deleted_to_customers.rb
- db/schema.rb
- test/fixtures/cart_items.yml
- test/fixtures/orders.yml
- test/models/cart_item_test.rb
- test/models/order_test.rb
customer,crte_item,order model　作成、カラム追加
> Customer,crte_item,order model create

- app/models/genre.rb
- app/models/item.rb
- app/models/shipping_address.rb
- db/migrate/20200223030942_create_items.rb
- db/migrate/20200223033925_create_shipping_addresses.rb
- db/migrate/20200223034345_create_genres.rb
- db/schema.rb
- test/fixtures/genres.yml
- test/fixtures/items.yml
- test/fixtures/shipping_addresses.yml
- test/models/genre_test.rb
- test/models/item_test.rb
- test/models/shipping_address_test.rb
Genre Item and  Shipping_adressのモデルを作成しました。
> Genre Item and  Shipping_adress

- app/models/cart_item.rb
- app/models/customer.rb
- app/models/genre.rb
- app/models/item.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/models/shipping_address.rb
> model_association add

- app/controllers/application_controller.rb
- app/controllers/customers/items_controller.rb
- app/views/admins/items/show.html.erb
- config/routes.rb
- db/schema.rb
アプリケーションコントローラの作成
pullしてから作業しよう！
> homes_show add

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/views/customers/homes/top.html.erb
- app/views/customers/registrations/new.html.erb
- app/views/customers/sessions/new.html.erb
- app/views/layouts/application.html.erb
> login logup 

- Gemfile.lock
- app/controllers/customers/customers_controller.rb
- app/views/customers/customers/show.html.erb
customerのマイページを作成中です。井原さんのデータが必要なため、プルリクし最新の状態をマージします。
> customer-show

- Gemfile.lock
- app/controllers/application_controller.rb
- app/views/customers/customers/exit.html.erb
- app/views/layouts/application.html.erb
- db/schema.rb
> heder create

- Gemfile.lock
- app/assets/stylesheets/sessions.scss
- app/views/admins/sessions/new.html.erb
> [Add]adminログイン画面view

- app/controllers/application_controller.rb
- app/controllers/customers/customers_controller.rb
- app/controllers/customers/registrations_controller.rb
- app/views/customers/customers/edit.html.erb
- app/views/customers/customers/show.html.erb
- config/routes.rb
- db/schema.rb
> Customers show

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/items.scss
- app/controllers/admins/items_controller.rb
- app/models/item.rb
- app/views/admins/items/new.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- db/schema.rb
admins_items_new 　完成（仮）最後綺麗にレイアウト整える
> Admins new item

- app/assets/stylesheets/customers.scss
- app/controllers/admins/customers_controller.rb
- app/controllers/admins/sessions_controller.rb
- app/controllers/customers/registrations_controller.rb
- app/views/admins/customers/show.html.erb
- app/views/admins/sessions/new.html.erb
> Admin order show

- app/controllers/admins/items_controller.rb
- app/views/admins/items/index.html.erb
- app/views/admins/items/new.html.erb
- app/views/layouts/application.html.erb
- db/migrate/20200226053918_rename__colum_to_genre.rb
- db/schema.rb
管理者の商品一覧作成済み
ジャンル、ステータスができていないため
新商品の登録不可
> admins_items_index Finish

- app/controllers/admins/customers_controller.rb
- app/views/admins/customers/index.html.erb
> [Finish]adimin会員一覧ページ

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/customers/registrations_controller.rb
- app/controllers/customers/shipping_addresses_controller.rb
- app/views/customers/cart_items/index.html.erb
- app/views/customers/shipping_addresses/index.html.erb
- config/routes.rb
> shipping_address_create

- app/views/admins/sessions/new.html.erb
> [Finish]admin会員編集ページ

- app/controllers/admins/customers_controller.rb
- app/views/admins/customers/edit.html.erb
- config/routes.rb
> [Finish]admin会員編集のページ

- app/controllers/admins/genres_controller.rb
- app/controllers/admins/items_controller.rb
- app/views/admins/genres/index.html.erb
- app/views/admins/items/new.html.erb
- config/routes.rb
> admin_genre_index Finish

- app/controllers/customers/shipping_addresses_controller.rb
- app/views/customers/shipping_addresses/edit.html.erb
- app/views/customers/shipping_addresses/index.html.erb
- config/routes.rb
- db/schema.rb
> shipping_address_edit_finish

- app/controllers/admins/genres_controller.rb
- app/controllers/admins/items_controller.rb
- app/controllers/admins/sessions_controller.rb
- app/models/genre.rb
- app/views/admins/genres/edit.html.erb
- app/views/admins/genres/index.html.erb
- app/views/admins/items/index.html.erb
- app/views/admins/items/new.html.erb
- config/routes.rb
- db/migrate/20200223034345_create_genres.rb
- db/migrate/20200227073934_add_deleted_at_to_genres.rb
- db/schema.rb
> Admins genres edit

- app/assets/stylesheets/homes.scss
- app/controllers/admins/homes_controller.rb
- app/controllers/admins/sessions_controller.rb
- app/views/admins/homes/top.html.erb
- config/routes.rb
> [Finish]adminトップ画面

- app/controllers/customers/customers_controller.rb
- app/controllers/customers/shipping_addresses_controller.rb
- app/views/customers/customers/edit.html.erb
- app/views/customers/customers/exit.html.erb
- app/views/customers/customers/show.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
customerの退会ページ、マイページ及び編集ページの編集を行いました。
> customers_show_edit_update_exit edit

- app/controllers/admins/orders_controller.rb
- app/views/admins/orders/index.html.erb
> [Add]admin_order_index

- app/controllers/customers/cart_items_controller.rb
- app/controllers/customers/items_controller.rb
- app/views/customers/items/show.html.erb
- config/routes.rb
itemのshowページを作成しました。カートに入れると保存できる機能も実装しました。次はカート一覧画面を作成していきます。
> items_show_create

- app/controllers/customers/orders_controller.rb
- app/views/customers/orders/new.html.erb
- app/views/layouts/_adminshead.html.erb
- app/views/layouts/_customershead.html.erb
- config/routes.rb
> Customers oders edit

- app/controllers/customers/cart_items_controller.rb
- app/controllers/customers/customers_controller.rb
- app/controllers/customers/orders_controller.rb
- app/views/customers/cart_items/index.html.erb
- app/views/customers/items/index.html.erb
- app/views/customers/items/show.html.erb
- config/routes.rb
> Cart item index

- app/assets/stylesheets/homes.scss
- app/controllers/customers/homes_controller.rb
- app/views/customers/homes/top.html.erb
> [Fixed]customer_top,customert_sign_up

- app/assets/stylesheets/homes.scss
- app/controllers/customers/cart_items_controller.rb
- app/controllers/customers/customers_controller.rb
- app/controllers/customers/homes_controller.rb
- app/controllers/customers/items_controller.rb
- app/controllers/customers/shipping_addresses_controller.rb
- app/views/customers/homes/top.html.erb
- app/views/customers/items/index.html.erb
custoerの詳細ページやカートに他人がアクセスできないようにしました。商品一覧でジャンル検索を押すとそのジャンルに関連する商品が表示されるようにしました。
> Customer fix

- app/controllers/customers/orders_controller.rb
- app/views/customers/customers/show.html.erb
- app/views/customers/items/index.html.erb
- app/views/customers/items/show.html.erb
- app/views/customers/orders/index.html.erb
- app/views/customers/orders/show.html.erb
- app/views/layouts/application.html.erb
> [Create]order_index

- app/controllers/customers/orders_controller.rb
- app/models/order.rb
- app/views/customers/orders/check.html.erb
- app/views/customers/orders/new.html.erb
- app/views/customers/orders/show.html.erb
> customers_orders_history finish

- app/controllers/admins/orders_controller.rb
- app/models/order.rb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/show.html.erb
- config/application.rb
- config/initializers/time_formats.rb
> [Finished]admin_order_index

- app/controllers/customers/orders_controller.rb
- app/models/order_detail.rb
- app/views/customers/customers/show.html.erb
- app/views/customers/orders/index.html.erb
- app/views/customers/orders/show.html.erb
item_indexの不具合を修正しました。マイページに注文履歴一覧のリンクを設定しました。
> [Fix]item-index

- app/controllers/admins/orders_controller.rb
- app/models/order_detail.rb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/show.html.erb
- config/routes.rb
> [Finished]admins_order_show

- app/assets/stylesheets/customers.scss
- app/controllers/admins/items_controller.rb
- app/controllers/customers/items_controller.rb
- app/views/customers/customers/edit.html.erb
- app/views/customers/customers/show.html.erb
- app/views/customers/items/index.html.erb
- app/views/customers/items/show.html.erb
- app/views/customers/orders/index.html.erb
- app/views/customers/orders/show.html.erb
- app/views/customers/shipping_addresses/index.html.erb
> Customer add

- app/controllers/admins/customers_controller.rb
- app/controllers/admins/genres_controller.rb
- app/controllers/admins/homes_controller.rb
- app/controllers/admins/items_controller.rb
- app/controllers/admins/orders_controller.rb
- app/controllers/customers/customers_controller.rb
- app/controllers/customers/homes_controller.rb
- app/controllers/customers/items_controller.rb
- app/controllers/customers/orders_controller.rb
- app/controllers/customers/shipping_addresses_controller.rb
- app/views/admins/orders/show.html.erb
- app/views/customers/customers/edit.html.erb
adminとcustomerのアクセス制限
customertopのコントローラ変更
> [Finish]admin,customerアクセス制限

- app/controllers/admins/items_controller.rb
- app/controllers/customers/customers_controller.rb
- app/controllers/customers/orders_controller.rb
- app/controllers/customers/shipping_addresses_controller.rb
- app/models/customer.rb
- app/models/order.rb
- app/models/shipping_address.rb
- app/views/admins/items/edit.html.erb
- app/views/customers/cart_items/index.html.erb
- app/views/customers/customers/edit.html.erb
- app/views/customers/customers/show.html.erb
- app/views/customers/items/show.html.erb
- app/views/customers/orders/check.html.erb
- app/views/customers/orders/new.html.erb
- app/views/customers/orders/show.html.erb
- app/views/customers/registrations/edit.html.erb
- app/views/customers/shipping_addresses/edit.html.erb
- app/views/customers/shipping_addresses/index.html.erb
配送先の新規登録と更新、マイパージの編集気のにバリデーションの設定を行いました。
> validation

- app/controllers/customers/items_controller.rb
- app/models/item.rb
- app/views/admins/items/edit.html.erb
- app/views/admins/items/index.html.erb
- app/views/admins/items/new.html.erb
- app/views/admins/items/show.html.erb
- app/views/customers/homes/about.html.erb
- app/views/customers/orders/index.html.erb
- db/migrate/20200304113730_reame_sales_atatus_column_to_items.rb
- db/schema.rb
> karamu finish
